/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum COLLISION_SHAPE_TYPE {
  COLLISION_SHAPE_BOX = 0,
  COLLISION_SHAPE_SPHERE,
  COLLISION_SHAPE_CONE,
  COLLISION_SHAPE_CAPSULE,
  COLLISION_SHAPE_CYLINDER,
  COLLISION_SHAPE_CONVEX_HULL,
  COLLISION_SHAPE_TRIANGLE_MESH
}
