//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum LIGHT_TYPES {
  LIGHT_POINT = 0,
  LIGHT_SPOT,
  LIGHT_DIRECTIONAL
}
