/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_BLENDING_MODES {
  M_BLENDING_NONE = 0,
  M_BLENDING_ALPHA,
  M_BLENDING_ADD,
  M_BLENDING_SUB,
  M_BLENDING_LIGHT,
  M_BLENDING_PRODUCT
}
