/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_BUFFER_TYPES {
  M_BUFFER_COLOR = 2,
  M_BUFFER_DEPTH = 4,
  M_BUFFER_STENCIL = 8
}
