/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_CULL_MODES {
  M_CULL_NONE = 0,
  M_CULL_FRONT,
  M_CULL_BACK,
  M_CULL_FRONT_BACK
}
