/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_DEPTH_MODES {
  M_DEPTH_NONE = 0,
  M_DEPTH_ALWAYS,
  M_DEPTH_LESS,
  M_DEPTH_GREATER,
  M_DEPTH_EQUAL,
  M_DEPTH_LEQUAL,
  M_DEPTH_GEQUAL,
  M_DEPTH_NOTEQUAL
}
