/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_FRAME_BUFFER_ATTACHMENT {
  M_ATTACH_DEPTH = 0,
  M_ATTACH_STENCIL,
  M_ATTACH_COLOR0,
  M_ATTACH_COLOR1,
  M_ATTACH_COLOR2,
  M_ATTACH_COLOR3,
  M_ATTACH_COLOR4,
  M_ATTACH_COLOR5,
  M_ATTACH_COLOR6,
  M_ATTACH_COLOR7
}
