/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_MATRIX_MODES {
  M_MATRIX_MODELVIEW = 0,
  M_MATRIX_PROJECTION,
  M_MATRIX_TEXTURE
}
