/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_PRIMITIVE_TYPES {
  M_PRIMITIVE_POINTS = 0,
  M_PRIMITIVE_LINES,
  M_PRIMITIVE_LINE_LOOP,
  M_PRIMITIVE_LINE_STRIP,
  M_PRIMITIVE_TRIANGLES,
  M_PRIMITIVE_TRIANGLE_STRIP,
  M_PRIMITIVE_TRIANGLE_FAN
}
