/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_RENDER_BUFFER_MODES {
  M_RENDER_DEPTH = 0,
  M_RENDER_STENCIL,
  M_RENDER_DEPTH_STENCIL
}
