/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_SOUND_FORMAT {
  M_SOUND_FORMAT_MONO8 = 0,
  M_SOUND_FORMAT_MONO16,
  M_SOUND_FORMAT_STEREO8,
  M_SOUND_FORMAT_STEREO16
}
