/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_STENCIL_FUNCS {
  M_STENCIL_ALWAYS = 0,
  M_STENCIL_NEVER,
  M_STENCIL_EQUAL,
  M_STENCIL_NOTEQUAL,
  M_STENCIL_LESS,
  M_STENCIL_LEQUAL,
  M_STENCIL_GREATER,
  M_STENCIL_GEQUAL
}
