/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_STENCIL_OPS {
  M_STENCIL_KEEP = 0,
  M_STENCIL_INVERT,
  M_STENCIL_DECR,
  M_STENCIL_INCR,
  M_STENCIL_REPLACE
}
