/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_TEX_COMBINE_MODES {
  M_TEX_COMBINE_REPLACE = 0,
  M_TEX_COMBINE_MODULATE,
  M_TEX_COMBINE_ALPHA,
  M_TEX_COMBINE_ADD,
  M_TEX_COMBINE_SUB,
  M_TEX_COMBINE_DOT
}
