/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_TEX_MODES {
  M_DEPTH = 0,
  M_R = 1,
  M_RG = 2,
  M_RGB = 3,
  M_RGBA = 4
}
