/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_TEX_FILTER_MODES {
  M_TEX_FILTER_NEAREST = 0,
  M_TEX_FILTER_NEAREST_MIPMAP_NEAREST,
  M_TEX_FILTER_NEAREST_MIPMAP_LINEAR,
  M_TEX_FILTER_LINEAR,
  M_TEX_FILTER_LINEAR_MIPMAP_NEAREST,
  M_TEX_FILTER_LINEAR_MIPMAP_LINEAR
}
