/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_TEX_GEN_MODES {
  M_TEX_GEN_NONE = 0,
  M_TEX_GEN_SPHERE_MAP,
  M_TEX_GEN_CUBE_MAP
}
