/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_TYPES {
  M_BOOL = 0,
  M_BYTE,
  M_UBYTE,
  M_SHORT,
  M_USHORT,
  M_INT,
  M_UINT,
  M_FLOAT,
  M_DOUBLE
}
