/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum M_VBO_MODES {
  M_VBO_STATIC = 0,
  M_VBO_DYNAMIC,
  M_VBO_STREAM
}
