/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class MColor : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MColor(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MColor obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MColor() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NeoNativeEnginePINVOKE.delete_MColor(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public byte r {
    set {
      NeoNativeEnginePINVOKE.MColor_r_set(swigCPtr, value);
    } 
    get {
      byte ret = NeoNativeEnginePINVOKE.MColor_r_get(swigCPtr);
      return ret;
    } 
  }

  public byte g {
    set {
      NeoNativeEnginePINVOKE.MColor_g_set(swigCPtr, value);
    } 
    get {
      byte ret = NeoNativeEnginePINVOKE.MColor_g_get(swigCPtr);
      return ret;
    } 
  }

  public byte b {
    set {
      NeoNativeEnginePINVOKE.MColor_b_set(swigCPtr, value);
    } 
    get {
      byte ret = NeoNativeEnginePINVOKE.MColor_b_get(swigCPtr);
      return ret;
    } 
  }

  public byte a {
    set {
      NeoNativeEnginePINVOKE.MColor_a_set(swigCPtr, value);
    } 
    get {
      byte ret = NeoNativeEnginePINVOKE.MColor_a_get(swigCPtr);
      return ret;
    } 
  }

  public MColor() : this(NeoNativeEnginePINVOKE.new_MColor__SWIG_0(), true) {
  }

  public MColor(byte newR, byte newG, byte newB, byte newA) : this(NeoNativeEnginePINVOKE.new_MColor__SWIG_1(newR, newG, newB, newA), true) {
  }

  public MColor(MColor color) : this(NeoNativeEnginePINVOKE.new_MColor__SWIG_2(MColor.getCPtr(color)), true) {
    if (NeoNativeEnginePINVOKE.SWIGPendingException.Pending) throw NeoNativeEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public MColor(MVector3 color) : this(NeoNativeEnginePINVOKE.new_MColor__SWIG_3(MVector3.getCPtr(color)), true) {
    if (NeoNativeEnginePINVOKE.SWIGPendingException.Pending) throw NeoNativeEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public MColor(MVector4 color) : this(NeoNativeEnginePINVOKE.new_MColor__SWIG_4(MVector4.getCPtr(color)), true) {
    if (NeoNativeEnginePINVOKE.SWIGPendingException.Pending) throw NeoNativeEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void set(byte newR, byte newG, byte newB, byte newA) {
    NeoNativeEnginePINVOKE.MColor_set(swigCPtr, newR, newG, newB, newA);
  }

}
