/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class MDataManager : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MDataManager(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MDataManager obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MDataManager() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NeoNativeEnginePINVOKE.delete_MDataManager(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void clear() {
    NeoNativeEnginePINVOKE.MDataManager_clear(swigCPtr);
  }

  public void addRef(MDataRef arg0) {
    NeoNativeEnginePINVOKE.MDataManager_addRef(swigCPtr, MDataRef.getCPtr(arg0));
  }

  public MDataRef getRef(uint id) {
    global::System.IntPtr cPtr = NeoNativeEnginePINVOKE.MDataManager_getRef(swigCPtr, id);
    MDataRef ret = (cPtr == global::System.IntPtr.Zero) ? null : new MDataRef(cPtr, false);
    return ret;
  }

  public uint getRefsNumber() {
    uint ret = NeoNativeEnginePINVOKE.MDataManager_getRefsNumber(swigCPtr);
    return ret;
  }

  public MDataManager() : this(NeoNativeEnginePINVOKE.new_MDataManager(), true) {
  }

}
