/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class MDataLoadFunction : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MDataLoadFunction(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MDataLoadFunction obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MDataLoadFunction() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NeoNativeEnginePINVOKE.delete_MDataLoadFunction(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public MDataLoadFunction(SWIGTYPE_p_f_p_q_const__char_p_void__bool functionPtr) : this(NeoNativeEnginePINVOKE.new_MDataLoadFunction(SWIGTYPE_p_f_p_q_const__char_p_void__bool.getCPtr(functionPtr)), true) {
  }

  public SWIGTYPE_p_f_p_q_const__char_p_void__bool m_functionPtr {
    set {
      NeoNativeEnginePINVOKE.MDataLoadFunction_m_functionPtr_set(swigCPtr, SWIGTYPE_p_f_p_q_const__char_p_void__bool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = NeoNativeEnginePINVOKE.MDataLoadFunction_m_functionPtr_get(swigCPtr);
      SWIGTYPE_p_f_p_q_const__char_p_void__bool ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_q_const__char_p_void__bool(cPtr, false);
      return ret;
    } 
  }

}
