/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class MDataRef : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MDataRef(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MDataRef obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MDataRef() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NeoNativeEnginePINVOKE.delete_MDataRef(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void clear() {
    NeoNativeEnginePINVOKE.MDataRef_clear(swigCPtr);
  }

  public virtual void destroy() {
    NeoNativeEnginePINVOKE.MDataRef_destroy(swigCPtr);
  }

  public void incrScore() {
    NeoNativeEnginePINVOKE.MDataRef_incrScore(swigCPtr);
  }

  public void decrScore() {
    NeoNativeEnginePINVOKE.MDataRef_decrScore(swigCPtr);
  }

  public uint getScore() {
    uint ret = NeoNativeEnginePINVOKE.MDataRef_getScore(swigCPtr);
    return ret;
  }

  public virtual void update() {
    NeoNativeEnginePINVOKE.MDataRef_update(swigCPtr);
  }

  public virtual int getType() {
    int ret = NeoNativeEnginePINVOKE.MDataRef_getType(swigCPtr);
    return ret;
  }

  public void setTime(int time) {
    NeoNativeEnginePINVOKE.MDataRef_setTime(swigCPtr, time);
  }

  public int getTime() {
    int ret = NeoNativeEnginePINVOKE.MDataRef_getTime(swigCPtr);
    return ret;
  }

  public string getFilename() {
    string ret = NeoNativeEnginePINVOKE.MDataRef_getFilename(swigCPtr);
    return ret;
  }

}
