/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class MDataLoader : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MDataLoader(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MDataLoader obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MDataLoader() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NeoNativeEnginePINVOKE.delete_MDataLoader(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public MDataLoader() : this(NeoNativeEnginePINVOKE.new_MDataLoader(), true) {
  }

  public void clear() {
    NeoNativeEnginePINVOKE.MDataLoader_clear(swigCPtr);
  }

  public void addLoader(SWIGTYPE_p_f_p_q_const__char_p_void__bool functionPtr) {
    NeoNativeEnginePINVOKE.MDataLoader_addLoader(swigCPtr, SWIGTYPE_p_f_p_q_const__char_p_void__bool.getCPtr(functionPtr));
  }

  public bool loadData(string filename, SWIGTYPE_p_void data) {
    bool ret = NeoNativeEnginePINVOKE.MDataLoader_loadData(swigCPtr, filename, SWIGTYPE_p_void.getCPtr(data));
    return ret;
  }

}
