/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class MSound : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MSound(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MSound obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MSound() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NeoNativeEnginePINVOKE.delete_MSound(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public MSound() : this(NeoNativeEnginePINVOKE.new_MSound(), true) {
  }

  public void create(M_SOUND_FORMAT format, uint size, uint sampleRate) {
    NeoNativeEnginePINVOKE.MSound_create(swigCPtr, (int)format, size, sampleRate);
  }

  public SWIGTYPE_p_void getData() {
    global::System.IntPtr cPtr = NeoNativeEnginePINVOKE.MSound_getData(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public M_SOUND_FORMAT getFormat() {
    M_SOUND_FORMAT ret = (M_SOUND_FORMAT)NeoNativeEnginePINVOKE.MSound_getFormat(swigCPtr);
    return ret;
  }

  public uint getSampleRate() {
    uint ret = NeoNativeEnginePINVOKE.MSound_getSampleRate(swigCPtr);
    return ret;
  }

  public uint getSize() {
    uint ret = NeoNativeEnginePINVOKE.MSound_getSize(swigCPtr);
    return ret;
  }

}
