/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class MVector2 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MVector2(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MVector2 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MVector2() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NeoNativeEnginePINVOKE.delete_MVector2(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public float x {
    set {
      NeoNativeEnginePINVOKE.MVector2_x_set(swigCPtr, value);
    } 
    get {
      float ret = NeoNativeEnginePINVOKE.MVector2_x_get(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      NeoNativeEnginePINVOKE.MVector2_y_set(swigCPtr, value);
    } 
    get {
      float ret = NeoNativeEnginePINVOKE.MVector2_y_get(swigCPtr);
      return ret;
    } 
  }

  public MVector2() : this(NeoNativeEnginePINVOKE.new_MVector2__SWIG_0(), true) {
  }

  public MVector2(float newX, float newY) : this(NeoNativeEnginePINVOKE.new_MVector2__SWIG_1(newX, newY), true) {
  }

  public MVector2(float value) : this(NeoNativeEnginePINVOKE.new_MVector2__SWIG_2(value), true) {
  }

  public MVector2(SWIGTYPE_p_float values) : this(NeoNativeEnginePINVOKE.new_MVector2__SWIG_3(SWIGTYPE_p_float.getCPtr(values)), true) {
  }

  public MVector2(MVector2 vec) : this(NeoNativeEnginePINVOKE.new_MVector2__SWIG_4(MVector2.getCPtr(vec)), true) {
    if (NeoNativeEnginePINVOKE.SWIGPendingException.Pending) throw NeoNativeEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public MVector2(MVector3 vec) : this(NeoNativeEnginePINVOKE.new_MVector2__SWIG_5(MVector3.getCPtr(vec)), true) {
    if (NeoNativeEnginePINVOKE.SWIGPendingException.Pending) throw NeoNativeEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void set(float newX, float newY) {
    NeoNativeEnginePINVOKE.MVector2_set(swigCPtr, newX, newY);
  }

  public void loadIdentity() {
    NeoNativeEnginePINVOKE.MVector2_loadIdentity(swigCPtr);
  }

  public void normalize() {
    NeoNativeEnginePINVOKE.MVector2_normalize(swigCPtr);
  }

  public void rotate(float angle) {
    NeoNativeEnginePINVOKE.MVector2_rotate(swigCPtr, angle);
  }

  public MVector2 getNormalized() {
    MVector2 ret = new MVector2(NeoNativeEnginePINVOKE.MVector2_getNormalized(swigCPtr), true);
    return ret;
  }

  public MVector2 getRotated(float angle) {
    MVector2 ret = new MVector2(NeoNativeEnginePINVOKE.MVector2_getRotated(swigCPtr, angle), true);
    return ret;
  }

  public float getAngleBetween(MVector2 vec) {
    float ret = NeoNativeEnginePINVOKE.MVector2_getAngleBetween(swigCPtr, MVector2.getCPtr(vec));
    if (NeoNativeEnginePINVOKE.SWIGPendingException.Pending) throw NeoNativeEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float getLength() {
    float ret = NeoNativeEnginePINVOKE.MVector2_getLength(swigCPtr);
    return ret;
  }

  public float getSquaredLength() {
    float ret = NeoNativeEnginePINVOKE.MVector2_getSquaredLength(swigCPtr);
    return ret;
  }

  public float dotProduct(MVector2 vec) {
    float ret = NeoNativeEnginePINVOKE.MVector2_dotProduct(swigCPtr, MVector2.getCPtr(vec));
    if (NeoNativeEnginePINVOKE.SWIGPendingException.Pending) throw NeoNativeEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MVector2 lerp(MVector2 vec, float factor) {
    MVector2 ret = new MVector2(NeoNativeEnginePINVOKE.MVector2_lerp(swigCPtr, MVector2.getCPtr(vec), factor), true);
    if (NeoNativeEnginePINVOKE.SWIGPendingException.Pending) throw NeoNativeEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
