//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum TEXT_ALIGN_MODES {
  TEXT_ALIGN_LEFT = 0,
  TEXT_ALIGN_RIGHT,
  TEXT_ALIGN_CENTER
}
